//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;

namespace Clide.Properties
{
	///	<summary>
	///	Provides access to string resources.
	///	</summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	static partial class Strings
	{
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class CommandManager
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	In order to register command instance '{command}', it must have a [Command] attribute.
			/// </summary>
			public static string CommandAttributeMissing(object command)
			{
				return Resources.CommandManager_CommandAttributeMissing.FormatWith(new 
				{
					command = command,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	In order to register command filter instance '{filter}', it must have a [CommandFilter] attribute.
			/// </summary>
			public static string CommandFilterAttributeMissing(object filter)
			{
				return Resources.CommandManager_CommandFilterAttributeMissing.FormatWith(new 
				{
					filter = filter,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Command type '{type}' does not have the required attribute '{attribute}'.
			/// </summary>
			public static string OwningPackageAttributeRequired(object type, object attribute)
			{
				return Resources.CommandManager_OwningPackageAttributeRequired.FormatWith(new 
				{
					type = type,
					attribute = attribute,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Command type '{type}' specifies owning package with id '{packageId}' but it could not be found or loaded.
			/// </summary>
			public static string OwningPackageNotFound(object type, object packageId)
			{
				return Resources.CommandManager_OwningPackageNotFound.FormatWith(new 
				{
					type = type,
					packageId = packageId,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Command type '{type}' specifies owning package with id '{packageId}' which is not a valid service provider.
			/// </summary>
			public static string OwningPackageNotServiceProvider(object type, object packageId)
			{
				return Resources.CommandManager_OwningPackageNotServiceProvider.FormatWith(new 
				{
					type = type,
					packageId = packageId,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	In order to register all commands for a given package automatically, the owning package '{package}' must have a [Guid] attribute applied, which must match the commands' corresponding [Command] attribute.
			/// </summary>
			public static string PackageGuidMissing(object package)
			{
				return Resources.CommandManager_PackageGuidMissing.FormatWith(new 
				{
					package = package,
				});
			}
		}
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class Diagnostics
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Failed to create output window for diagnostics traces.
			/// </summary>
			public static string FailedToCreateOutputWindow { get { return Resources.Diagnostics_FailedToCreateOutputWindow; } }
		}
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class SettingsManager
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Cannot persist setting value of type '{0}' from property '{1}.{2}'. An appropriate type converter that can convert the value to a string is required.
			/// </summary>
			public static string CannotSaveAsString(object arg0, object arg1, object arg2)
			{
				return Resources.SettingsManager_CannotSaveAsString.FormatWith(new 
				{
					arg0 = arg0,
					arg1 = arg1,
					arg2 = arg2,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Failed to read settings class '{0}' from the settings store.
			/// </summary>
			public static string FailedToRead(object arg0)
			{
				return Resources.SettingsManager_FailedToRead.FormatWith(new 
				{
					arg0 = arg0,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Cannot assign value of type '{0}' to property '{1}.{2}' of type '{3}'. An appropriate type converter is required.
			/// </summary>
			public static string InvalidValue(object arg0, object arg1, object arg2, object arg3)
			{
				return Resources.SettingsManager_InvalidValue.FormatWith(new 
				{
					arg0 = arg0,
					arg1 = arg1,
					arg2 = arg2,
					arg3 = arg3,
				});
			}
		}
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class Settings
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Object has already been initialized.
			/// </summary>
			public static string AlreadyInitialized { get { return Resources.Settings_AlreadyInitialized; } }
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	EndEdit invoked without corresponding BeginEdit.
			/// </summary>
			public static string EndEditWithoutBeginEdit { get { return Resources.Settings_EndEditWithoutBeginEdit; } }
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	EndInit invoked without corresponding BeginInit.
			/// </summary>
			public static string EndInitWithoutBeginInit { get { return Resources.Settings_EndInitWithoutBeginInit; } }
		}
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class VsCommandExtensionAdapter
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Attempted to execute command '{commandText}' ({commandType}) but current command status does not allow it.
			/// </summary>
			public static string CannotExecute(object commandText, object commandType)
			{
				return Resources.VsCommandExtensionAdapter_CannotExecute.FormatWith(new 
				{
					commandText = commandText,
					commandType = commandType,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Command did not execute successfully due to an unexpected exception. Please check the output window for additional information.
			/// </summary>
			public static string ExecuteShieldMessage { get { return Resources.VsCommandExtensionAdapter_ExecuteShieldMessage; } }
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Executing command '{commandText}' ({commandType}).
			/// </summary>
			public static string ExecutingCommand(object commandText, object commandType)
			{
				return Resources.VsCommandExtensionAdapter_ExecutingCommand.FormatWith(new 
				{
					commandText = commandText,
					commandType = commandType,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Command could not determine its current status due to an unexpected exception. Please check the output window for additional information.
			/// </summary>
			public static string QueryStatusShieldMessage { get { return Resources.VsCommandExtensionAdapter_QueryStatusShieldMessage; } }
		}
	}
}

